### ISSUE TITLE
Decimal and Negative NumberSupport

### ISSUE THREAD

**Issue by testament** [bernii/gauge.js#16]
Hello, is there a way to show decimal values on the gauge?, also  there is a way to use a negative range?

**Comment by bernii** [comment]
Of course you can! I've updated gauge so it works with negative values too.

Regarding showing decimal values you just need to provide custom text renderer as default one is designed for integer values. A sample jsfiddle with negative/decimal values working and decimal values renderer here http://jsfiddle.net/berni/smNjl

**Comment by rajeevpn** [comment]
Firstly, thanks so much for this wonderful piece of work! We've been playing with it and it's awesome :-) 
One question though: We are trying to set this up for a range of say -20 to 20. We would like for the shading that happens when the gauge is set to a negative value to be the sector between 0 and the negative value and not from the left extreme to the value. Basically the orange area - (terribly sorry for the very poor 'skitch'ing of the image)
![screenshot_12-jun-13_8_30_pm](https://f.cloud.github.com/assets/4680335/643196/5e3fba10-d371-11e2-8fde-603f89e05493.png)
Any help appreciated!
thanks

**Comment by singhkumarhemant** [comment]
this fiddle is not alive. plz suggest any other demo

**Comment by Abhijeet-Tiwari** [comment]
Please provide a new fiddle! Above one not alive!

**Comment by SemihOzden** [comment]
Could you please provide another demo thank you!

**Comment by raphaeldas** [comment]
For everyone who wants to see the jsfiddle example: https://web.archive.org/web/20161226121513/http://jsfiddle.net/berni/smNjl
@SemihOzden @Abhijeet-Tiwari @singhkumarhemant
